parse:
  applicationId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  javascriptKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  masterKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

stripe:
  masterKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
